name: Less Advanced Security
description: Bring-your-own PR annotations to any tool which outputs sarif
author: '@eliblock'
inputs:
  github_app_id:
    required: true
    description: app id for GitHub application
  github_app_install_id:
    required: true
    description: install id from GitHub application
  github_app_key:
    required: true
    description: key from GitHub application. Will be placed in a temporary file and passed to less-advanced-security.
  sarif_path:
    required: true
    description: path to sarif file containing annotations
  filter_annotations:
    description: '"true" to apply annotations only when they coincide with a changed line, "false" apply all annotations'
    default: 'true'
  check_name:
    description: override of the default name for the check. When set, this string is used instead of the tool driver name found in the sarif.
    default: ''
runs:
  using: node16
  main: dist/index.js
